% =================================================================
% foundational_rules_clean.pl - FIXED VERSION
% =================================================================

% Simple utility predicate
member(X, [X|_]).
member(X, [_|T]) :- member(X, T).

% Basic predicate for person
person(Person) :- atom(Person).

% =================================================================
% DISABILITY STATUS
% =================================================================
disability_status(Person, true) :- vulnerable_group(Person, disabled).
disability_status(Person, false) :- person(Person), \+ vulnerable_group(Person, disabled).

% =================================================================
% VULNERABLE GROUP ELIGIBILITY
% =================================================================
vulnerable_group_eligible(Person) :- 
    vulnerable_group(Person, _).

% REMOVED: The gender→women vulnerable_group rule
% This was causing "Unknown procedure: gender/2" errors
% Python should generate vulnerable_group facts directly instead

% NOTE: All vulnerable_group facts are now generated by Python
% - is_disabled → vulnerable_group(Person, disabled)
% - is_senior_citizen → vulnerable_group(Person, senior_citizen)
% - is_widow → vulnerable_group(Person, widow)
% - is_single_parent → vulnerable_group(Person, single_parent)
% - is_transgender → vulnerable_group(Person, transgender)
% - gender=female → vulnerable_group(Person, women)
% - age<18 → vulnerable_group(Person, children) [if added to Python]

